# Generated by Django 5.2 on 2025-04-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('yayin_tarihi', models.DateTimeField(auto_now_add=True)),
                ('yazar', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='haber_fotolari/')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberlersitesi.kategori')),
            ],
        ),
    ]
